[features]
seeds = false
skip-lint = false
[programs.localnet]
cpi_pda = "8xEfwJb65GHD9fogdWWSxmt8gQj1eoCin1BCXC99FzC7"
worker = "9aLnL3iN99rJNz9VqQrEzijLDN5dcHfnCoitR6zbWYFM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yasushi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
